services:
  b3api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b3quotes_api
    ports:
      - "8083:8080"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
