services:
  b3api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b3quotes_api
    ports:
      - "8083:8080"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: b3quotes_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    depends_on:
      - b3api

volumes:
  sqlite_data:
